# Generated by Django 5.2.7 on 2025-10-13 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Consultorio',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('identifica', models.BigIntegerField()),
                        ('codigo_de', models.CharField(db_column='código_de', max_length=10)),
                        ('nombre_de', models.CharField(db_column='nombre_de_', max_length=100)),
                        ('nombre_del', models.CharField(db_column='nombre_del', max_length=100)),
                        ('telefono', models.CharField(db_column='teléfono', max_length=50)),
                        ('direccion', models.CharField(db_column='dirección', max_length=100)),
                        ('correo_ele', models.EmailField(db_column='correo_ele', max_length=254)),
                        ('tipo_de_pr', models.CharField(db_column='tipo_de_pr', max_length=100)),
                        ('clase_de_p', models.CharField(db_column='clase_de_p', max_length=50)),
                        ('codigo_loc', models.IntegerField(db_column='codigo_loc')),
                        ('codigo_upz', models.IntegerField(db_column='codigo_upz')),
                        ('coordenada', models.FloatField(db_column='coordenada')),
                        ('coordena_1', models.FloatField(db_column='coordena_1')),
                    ],
                    options={
                        'db_table': 'consultorios',
                        'managed': False,
                    },
                ),
            ],
        ),
        migrations.CreateModel(
            name='ConsultorioExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120)),
                ('comment', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='app.consultorio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
